# -*- coding: utf-8 -*-
"""Leaves.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFhtMRLVbK0K49QvF9S_DbrZcINpxjeI
"""

!pip install ultralytics

from ultralytics import YOLO

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="W23f16qA2Cv9m47qLNxK")
project = rf.workspace("toxic-plants").project("fallen-leaves-tph84")
version = project.version(4)
dataset = version.download("yolov11")

model = YOLO('yolo11n.pt')

import os
from ultralytics import YOLO

dataset_dir = os.path.abspath("/content/Fallen-Leaves-4")

# Define paths for train and validation images and labels
train_images_dir = os.path.join(dataset_dir, 'train', 'images')
val_images_dir = os.path.join(dataset_dir, 'valid', 'images')
# Assuming labels are stored in a 'labels' subdirectory within train and valid
train_labels_dir = os.path.join(dataset_dir, 'train', 'labels')
val_labels_dir = os.path.join(dataset_dir, 'valid', 'labels')

dataset = version.download("yolov11")
results = model.train(data="/content/Fallen-Leaves-4/data.yaml", epochs=1, imgsz=128,save=True,save_period=5,time=10)

results = model(source="/content/Fallen-Leaves-4/train/images", conf=0.005)
for result in results:
    result.show()

from ultralytics import YOLO
import cv2
import numpy as np

colors = {
    'red': ([0, 50, 50], [10, 255, 255]),  # Dirt
    'brown': ([10, 35, 50], [45, 255, 255]),  # Dead leaves/grass (Adjusted)
    'green': ([35, 80, 20], [55, 255, 255]),  # Grass/greenery (Adjusted)
    'purple': ([120, 50, 30], [160, 255, 255]),  # Purple flowers
    'yellow': ([20, 100, 100], [30, 255, 255]),  # Yellow flowers
    'white': ([0, 0, 150], [180, 50, 255])  # Snow
}

from ultralytics import YOLO
import cv2
import numpy as np
from google.colab.patches import cv2_imshow # Import the cv2_imshow function


# This method is used to detect the colors of each plant
def detect_colors(image_path, overlap=True):
    """
    Detects colors in an image using YOLO and displays the results.

    Args:
        image_path (str): The path to the input image.
        overlap (bool): Whether to allow overlapping colors.
    """
    img = cv2.imread(image_path)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    #hsv uses hue, saturation, and brightness

    color_masks = {} # Empty dictionary to store color masks


    # Convert the image to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply adaptive thresholding
    thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY_INV, 11, 2)

    # Find contours of white regions. This is used in detecting snow and other white things in images.
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Draw contours on the original image (or process as needed)
    cv2.drawContours(img, contours, -1, (255, 255, 255), 2)
    for color_name, (lower, upper) in colors.items():
        mask = cv2.inRange(hsv, np.array(lower), np.array(upper))
        color_masks[color_name] = mask


        # Overlapping colors: simply display the masks on the original image
    for color_name, mask in color_masks.items():
        img[mask > 0] = colors[color_name][0]  # Color the detected regions where mask is greater than 0

    cv2_imshow(img) # Use cv2_imshow instead of cv2.imshow to display processed image.

import os
image_path = '/content/Fallen-Leaves-4/train/images'  # Path to your image directory
for filename in os.listdir(image_path):
    if filename.endswith(('.jpg', '.png', '.jpeg')):  # Filter for image files
        img_path = os.path.join(image_path, filename)  # Create the full image path
        detect_colors(img_path, overlap=True)  # With overlapping
        #detect_colors(img_path, overlap=False)  # Without overlapping