# -*- coding: utf-8 -*-
"""VirginiaCreeper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LPAd3rzFro_htkBCwvEatAxspPW6VdU
"""

!pip install ultralytics
from ultralytics import YOLO

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="W23f16qA2Cv9m47qLNxK")
project = rf.workspace("toxic-plants").project("virginia-creeper")
version = project.version(3)
dataset = version.download("yolov11")

model = YOLO('yolo11n.pt')
results = model.train(data="/content/Virginia-Creeper-3/data.yaml", epochs=1, imgsz=64,save=True,save_period=5,time=10)

results = model(source="/content/Virginia-Creeper-3/train/images",conf=0.005)
for result in results:
    result.show()